### ISSUE TITLE
raising Python error from C fails when too many errors are chained

### ISSUE THREAD

**Issue by folx** [OpenBXI/bxibase#9]
Library call to bxierr.BXICError.raise_if_ko leads to too many recursion when lot of errors are encounter (such as loading a large topology without RTs in bxiarchive-info):

> [C] bxiarchive-i Uncaught Exception - exiting thread
> [C] bxiarchive-i RuntimeError: maximum recursion depth exceeded while calling a Python object
> [T] bxiarchive-i <module> at .../bxifm/packaged/bin/bxiarchive-info:50
> [T] bxiarchive-i 	bxiio.load_tables(topology, args.archive)
> [T] bxiarchive-i load_tables at .../bxiapi/packaged/lib/bxi/api/io.py:303
> [T] bxiarchive-i 	bxierr.BXICError.raise_if_ko(err)
> [T] bxiarchive-i raise_if_ko at .../bxibase/packaged/lib/bxi/base/err.py:128
> [T] bxiarchive-i 	raise cls(bxierr_p)
> [T] bxiarchive-i __init__ at .../bxibase/packaged/lib/bxi/base/err.py:66
> [T] bxiarchive-i 	self.cause = BXICError(cause_, gc=False) if cause_ != __FFI__.NULL else None
> [...]
> [T] bxiarchive-i 	self.cause = BXICError(cause_, gc=False) if cause_ != __FFI__.NULL else None
> [T] bxiarchive-i __init__ at /mnt/vcs/hpcbxi/bxibase/packaged/lib/bxi/base/err.py:66
> [T] bxiarchive-i 	self.cause = BXICError(cause_, gc=False) if cause_ != __FFI__.NULL else None
> [T] bxiarchive-i __init__ at /mnt/vcs/hpcbxi/bxibase/packaged/lib/bxi/base/err.py:62
> [T] bxiarchive-i 	super(BXICError, self).__init__(err_msg)
> [T] bxiarchive-i __init__ at /mnt/vcs/hpcbxi/bxibase/packaged/lib/bxi/base/err.py:35
> [T] bxiarchive-i 	super(BXIError, self).__init__(msg)

**Comment by folx** [comment]
FYI
> $ ipython
> Python 2.7.12 (default, Apr 27 2017, 15:43:28)
> In [1]: import sys
> In [2]: print sys.getrecursionlimit()
> 1000

**Comment by jnquintin** [comment]
corrected in commit: b9acf19
